name: eccomerce_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  badges: ^3.1.2
  remixicon: ^1.2.0
  iconsax: ^0.0.8
  flutter_otp_text_field: ^1.2.0
  expandable_page_view: ^1.0.17
  image_picker: ^1.1.2
  mobile_scanner: ^5.2.3
  palette_generator: ^0.3.3+4
  flutter_rating_bar: ^4.0.1
  buttons_tabbar: ^1.3.13
  sms_autofill: ^2.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
